DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
    id BIGINT NOT NULL COMMENT 'Primary Key ID (snowflake)',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT 'Name',
    age INT NULL DEFAULT NULL COMMENT 'Age',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT 'Email',
    deleted INT NULL DEFAULT '0' COMMENT 'Logical Deletion Flag',
    department_id VARCHAR(30) NULL DEFAULT NULL COMMENT 'Department ID',
    create_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation Time',
    update_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update Time',
    PRIMARY KEY (id)
);