# Conversion to YAML from Properties formar report
# Errors:
# - Direct assignment 'spring=' can not be combined with sub-property assignment 'spring.application...'. Direct assignment is dropped!
spring:
  application:
    name: restservice
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/schema-h2.sql
      data-locations:
        - classpath:db/data-h2.sql
  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes in milliseconds
      cache-null-values: false
logging:
  level:
    "[com.example.restservice]": DEBUG
    "[com.baomidou.mybatisplus]": DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
  # writer-with-order-by-keys: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,traces
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    enable:
      all: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://collector:4317/v1/traces
