[SERVICE]
	Flush 1
	Log_Level debug
	Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
	Name tail
	Path /var/log/app/application.json.log
	Read_from_Head true
	Refresh_Interval 1
	Skip_Long_Lines On
	Parser json

[OUTPUT]
	Name es
	Host elasticsearch
	Port 9200
	Logstash_Format On
	Logstash_Prefix structured-logs
	Suppress_Type_Name On
	Trace_Error On
